// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8-EflESMWqCeFDlTGkZob3GWXAiDt2As',
    appId: '1:910173261033:android:1312be3c41b0761e7ff478',
    messagingSenderId: '910173261033',
    projectId: 'learn-flutter-to-do-app',
    storageBucket: 'learn-flutter-to-do-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFXqa21MRARlNh8Wkrxxz-GTOkgdi9kdg',
    appId: '1:910173261033:ios:a38757fa892e4e0e7ff478',
    messagingSenderId: '910173261033',
    projectId: 'learn-flutter-to-do-app',
    storageBucket: 'learn-flutter-to-do-app.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFXqa21MRARlNh8Wkrxxz-GTOkgdi9kdg',
    appId: '1:910173261033:ios:a38757fa892e4e0e7ff478',
    messagingSenderId: '910173261033',
    projectId: 'learn-flutter-to-do-app',
    storageBucket: 'learn-flutter-to-do-app.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );
}
